name: smart_dish
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.11
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  injectable: ^1.5.0
  kt_dart: ^0.10.0
  rxdart: ^0.27.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  auto_route: ^3.2.1
  uuid: ^3.0.5
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_core_platform_interface: ^4.2.3
  cloud_functions: ^3.2.4
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5
  image_picker: ^0.8.4+4
  implicitly_animated_reorderable_list: ^0.4.2
  flutter_hooks: ^0.18.2
  cloud_firestore_odm: ^1.0.0-dev.5
  crop_your_image: ^0.6.0+1
  font_awesome_flutter: ^9.2.0
  firebase_messaging_web: ^2.2.5
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.2.0
  overlay_support: ^1.2.1
  cached_network_image: ^3.2.0
  rename: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.2.1
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  logger: ^1.1.0
  fake_cloud_firestore: ^1.2.0
  mockito: ^5.0.17
  mocktail: ^0.2.0
  freezed: ^1.1.0
  firebase_auth_mocks: ^0.8.2
  flutter_launcher_icons: "^0.9.2"
  cloud_firestore_odm_generator: ^1.0.0-dev.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
